package generator

import (
	"html/template"
	"os"

	"github.com/nokacper24/static-templ/internal/finder"
)

const outputScript = `// Code generated by STATIC TEMPL; DO NOT EDIT.
package main

import (
	"context"
	"log"
	"os"
	"path/filepath"

	"github.com/a-h/templ"
	{{- range .Imports }}
	"{{ . }}"
	{{- end }}
)

func main() {
	components := []componentToGenerate{
	{{- range .FilesToGenerate }}
		{
			{{ .PackageName }}.{{ .FuncToCall }}(),
			"{{.FilePath}}",
		},
	{{- end }}
	}

	ctx := context.Background()

	for _, comp := range components {
		if err := os.MkdirAll(filepath.Dir(comp.path), os.ModePerm); err != nil {
			log.Fatal("error creating dirs:", err)
		}
	
		file, err := os.Create(comp.path)
		if err != nil {
			log.Fatal("error creating file:", err)
		}
		defer file.Close()
		if err = comp.component.Render(ctx, file); err != nil {
			log.Fatal("error rendering templ:", err)
		}
	}
}

type componentToGenerate struct {
	component templ.Component
	path      string
}
`

type InputData struct {
	Imports         []string
	FilesToGenerate []StringedData
}

type StringedData struct {
	FuncToCall  string
	FilePath    string
	PackageName string
}

func Generate(outputPath string, imports []string, funcs []finder.FileToGenerate) error {
	var stringed []StringedData
	for _, f := range funcs {
		stringed = append(stringed, StringedData{
			f.FunctionName,
			f.ToGenerate("web/pages", "dist"),
			f.PackageName,
		})
	}

	data := InputData{
		Imports:         imports,
		FilesToGenerate: stringed,
	}

	tmpl, err := template.New("output").Parse(outputScript)
	if err != nil {
		return err
	}

	f, err := os.Create(outputPath)
	if err != nil {
		return err
	}
	defer f.Close()

	err = tmpl.Execute(f, data)
	if err != nil {
		return err
	}

	return nil
}
